# Invalid CnfCertificationSuiteRun for testing purposes.
# Invalidation reason: config maps's data is empty.

apiVersion: cnf-certifications.redhat.com/v1alpha1
kind: CnfCertificationSuiteRun
metadata:
  labels:
    app.kubernetes.io/name: cnfcertificationsuiterun
    app.kubernetes.io/instance: cnfcertificationsuiterun-sample
    app.kubernetes.io/part-of: certsuite-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: certsuite-operator
  name: cnfcertificationsuiterun-invalid-sample4
  namespace: certsuite-operator
spec:
  # TODO(user): Add fields here
  labelsFilter: "observability"
  logLevel: "info"
  timeout: "2h"

  configMapName: "certsuite-invalid-config4"
  preflightSecretName : "certsuite-preflight-dockerconfig"
