apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: certsuite-operator-olm-catalog
  namespace: certsuite-operator
spec:
  sourceType: grpc
  image: quay.io/redhat-best-practices-for-k8s/certsuite-operator-catalog:v0.0.1
  displayName: OLM Test Catalog for the certsuite operator
  publisher: RedHat.com
  grpcPodConfig:
    securityContextConfig: restricted
