@startuml "Run Config"

map configMap1 {
data => tnf_config.yaml: |\n\
  targetNameSpaces:\n\
    - name: tnf\n\
  podsUnderTestLabels:\n\
    - "test-network-function.com/generic: target"\n\
  ...
}


map myFirstRun {
Kind => CnfCertificationSuiteRun
Name => myFirstRun

ConfigMap *--> configMap1
Labels => "telco && !observability-container-logging"
}

map mySecondRun {
Kind => CnfCertificationSuiteRun
Name => mySecondRun

ConfigMap *--> configMap1
Labels => "observability-container-logging"
}
@enduml