@startuml "Run Config"

map configMap1 {
data => tnf_config.yaml: |\n\
  targetNameSpaces:\n\
    - name: tnf\n\
  podsUnderTestLabels:\n\
    - "test-network-function.com/generic: target"\n\
  ...
}

map secret1 {
data => preflight_dockerconfig.json: |\n\
  eyAiYXV0aHMiOiB7fSB9Cg==
}

map myFirstRun {
Kind => CnfCertificationSuiteRun
Name => myFirstRun

ConfigMap *--> configMap1
Secret *--> secret1
Labels => "telco && !observability-container-logging"
}

map mySecondRun {
Kind => CnfCertificationSuiteRun
Name => mySecondRun

ConfigMap *--> configMap1
Secret *--> secret1
Labels => "observability-container-logging"
}
@enduml