## Append samples of your project ##
resources:
- cnf-certifications_v1alpha1_cnfcertificationsuiterun.yaml
- extra/certsuite-configmap.yaml
- extra/certsuite-preflight-secret.yaml

## Uncomment this two files (configmap+secret) to create a runnable test CR in the test namespace.
## Then run them with: oc kustomize config/samples | oc apply -f -
#- extra/certsuite-configmap.yaml
#- extra/certsuite-preflight-secret.yaml

#+kubebuilder:scaffold:manifestskustomizesamples

namespace: certsuite-operator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
